name: Seidlitz
favicon: null
layout_spectrum: 0.982266248902306
typography_spectrum: 0.9051721154246479
title: Seidlitz Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74681180-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d39c79'
    - '#efdccf'
    - '#d9aa8b'
    - '#e9cdba'
  brandStrength: 0.375
  lightness: 0.125
  saturation: 0.9939558650366962
  rhythmicContrast: 0.25
purpose: []
