name: Seidlitz
favicon: null
layout_spectrum: 0.50389
typography_spectrum: 0.85664
title: Seidlitz Consulting
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74681180-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d39c79'
    - '#efdccf'
    - '#d9aa8b'
    - '#e9cdba'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
