title: Seidlitz Consulting
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3446808
  brandStrength: 0.7170213
  lightness: 0.6446809
  brandColors:
    - '#000000'
    - '#5C4C5C'
    - '#382841'
    - '#6590D7'
    - '#2DA3EA'
  rhythmicContrast: 0.2234043
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-74681180-1
  facebook: null
favicon: null
name: Seidlitz
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.85664
layout_spectrum: 0.8212766
